name: 'user-web'
_port: 8021

# nacos
host: '10.120.21.77'
port: 8848
namespace: '73bb8093-63eb-4bf3-bd81-84b18fe259d6'
user: 'nacos'
password: 'nacos'
data_id: 'user-web.json'
group: 'dev'

goods_srv:
  host: '127.0.0.1'
  port: 50051
  name: 'goods_srv'

jwt:
  key: 'hTMHLwQFh^aLiyS8X&xvb7@zhNccyE$2'

sms:
  key: "xxxx"
  secret: "xxx"
  expire: 300

redis:
  host: '10.120.21.77'
  port: 6379

consul:
  host: "10.120.21.77"
  port: 8500