# Nacos
host: '10.120.21.77'
port: 8848
namespace: '73bb8093-63eb-4bf3-bd81-84b18fe259d6'
user: 'nacos'
password: 'nacos'
data_id: 'user-web.json'
group: 'pro'

name: 'user-web'
user_srv:
  host: '127.0.0.1'
  port: 50051