name: 'user-web'
port: 8021

user_srv:
  host: '127.0.0.1'
  port: 50051

jwt:
  key: 'hTMHLwQFh^aLiyS8X&xvb7@zhNccyE$2'

sms:
  key: "xxxx"
  secret: "xxx"
  expire: 300

redis:
  host: '10.120.21.77'
  port: 6379